// <auto-generated />
using System;
using MarieSkema.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarieSkema.Migrations
{
    [DbContext(typeof(SkemaDbContext))]
    [Migration("20250115124144_ConvertDageEnumToString")]
    partial class ConvertDageEnumToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarieSkema.Models.Fag", b =>
                {
                    b.Property<int>("FagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FagId"));

                    b.Property<string>("FagNavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("FagTid")
                        .HasColumnType("real");

                    b.Property<bool>("TPTid")
                        .HasColumnType("bit");

                    b.HasKey("FagId");

                    b.ToTable("Fag");
                });

            modelBuilder.Entity("MarieSkema.Models.FagDage", b =>
                {
                    b.Property<int>("FagDageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FagDageId"));

                    b.Property<string>("Dag")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("FagFagligeTimer")
                        .HasColumnType("real");

                    b.Property<int>("FagId")
                        .HasColumnType("int");

                    b.Property<int>("LaererId")
                        .HasColumnType("int");

                    b.Property<float>("TPTimer")
                        .HasColumnType("real");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("FagDageId");

                    b.HasIndex("FagId");

                    b.HasIndex("LaererId");

                    b.ToTable("FagDages");
                });

            modelBuilder.Entity("MarieSkema.Models.Laerer", b =>
                {
                    b.Property<int>("LaererId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaererId"));

                    b.Property<string>("LaererNavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LaererId");

                    b.ToTable("Laerer");
                });

            modelBuilder.Entity("MarieSkema.Models.FagDage", b =>
                {
                    b.HasOne("MarieSkema.Models.Fag", "Fag")
                        .WithMany("fagDageses")
                        .HasForeignKey("FagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarieSkema.Models.Laerer", "Laerer")
                        .WithMany("FagsDages")
                        .HasForeignKey("LaererId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fag");

                    b.Navigation("Laerer");
                });

            modelBuilder.Entity("MarieSkema.Models.Fag", b =>
                {
                    b.Navigation("fagDageses");
                });

            modelBuilder.Entity("MarieSkema.Models.Laerer", b =>
                {
                    b.Navigation("FagsDages");
                });
#pragma warning restore 612, 618
        }
    }
}
